### ISSUE TITLE
Title alignment

### ISSUE THREAD

**Issue by yannickgr** [yannickgr/PieWatchFace#12]
Title text should always show the start of the title and let the ending fade out (if it's long enough for that).
Currently, for event on the rights side, we only see the ending of the title. So it should be left-aligned to the center, not right-aligned to the edge.
We will probably calculate a offset away from the center so the start of the title is clearly visible.
Exception to the rule: if the title is short enough to fit completely on the screen, it should stay aligned to the edge of the screen, not the center, as this looks better and remains consistent.

**Comment by gurinderhans** [comment]
Left positioning from the center isn't perfect and should be calculated dynamically depending on the pie piece size.

**Comment by gurinderhans** [comment]
Closing for now since calculating positioning dynamically will cause inconsistency between each piece's titles
