### ISSUE TITLE
Event horizon

### ISSUE THREAD

**Issue by yannickgr** [yannickgr/PieWatchFace#5]
For aesthetic reasons it would be nice to have a short fadeout of our horizon. What I mean: before our current time indicator we display all-day events (if there are any). Before that is basically the horizon of events we can see for the next 12 (ish) hours. Basically we would have a blank pie piece there of about half an hour length which is a gradient from transparant to black, to serve as a nice separator.

![screen-shot-2015-11-23-at-12 56 20](https://cloud.githubusercontent.com/assets/15957852/11336404/593d5ff6-91e5-11e5-8ec3-9278c9094024.png)

**Comment by gurinderhans** [comment]
Is this not being done anymore?

**Comment by yannickgr** [comment]
Yes it's done. Committed it.
